version: "2"

run:
  timeout: 10m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - bodyclose
    - unconvert
    - unparam

formatters:
  enable:
    - gofmt
    - goimports